volumes:
  redis-volume:
    driver: local-persist
    driver_opts:
      mountpoint: ./data/redis

version: '3'
services:
  redis:
    image: redis:3.2.9
    command: redis-server --appendonly yes
    restart: always
    sysctls:
      # Required for some kernels
      - net.core.somaxconn=511
    volumes:
      - redis-volume:/data
  nginx:
    image: nginx:1.13.0
    command: /bin/bash -c "envsubst '${API_LOCATION},${UI_LOCATION}' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    volumes:
      - ./data:/data
      - ./data/nginx.conf:/etc/nginx/conf.d/mysite.template
    links:
      - console
    ports:
      - "80:80"
      - "443:443"
  console:
    build: ./dockerfiles/console
    environment:
      ANSIBLE_INVENTORY: /data/hosts
    links:
      - redis
    volumes:
      - .:/opt/app
      - ./data/:/data
      - ./data/ssh:/root/.ssh
    restart: always
    # command: /bin/bash -c "eval `ssh-agent -s`; ssh-agent bash; ssh-add ~/.ssh/id_rsa; ansible all -m ping; ansible-playbook /data/playbook.yml -f 10"
